[project]
name = "helper"
version = "0.1.0"
description = "Helper GUI and pipeline manager for NGS analysis"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "PyQt5",
    "pysam",
    "regex",
    "numpy",
    "scipy",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
