# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jarvis/git/Powercall2/Powercall/Add_tags.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(639, 683)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.treeWidget = QtWidgets.QTreeWidget(self.frame)
        self.treeWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(461, 548))
        self.treeWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treeWidget.setAcceptDrops(False)
        self.treeWidget.setAutoFillBackground(True)
        self.treeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.treeWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.treeWidget.setAutoExpandDelay(-1)
        self.treeWidget.setIndentation(20)
        self.treeWidget.setRootIsDecorated(True)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setAllColumnsShowFocus(False)
        self.treeWidget.setHeaderHidden(False)
        self.treeWidget.setColumnCount(1)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setCascadingSectionResizes(True)
        self.treeWidget.header().setDefaultSectionSize(300)
        self.treeWidget.header().setHighlightSections(False)
        self.treeWidget.header().setMinimumSectionSize(100)
        self.treeWidget.header().setSortIndicatorShown(False)
        self.treeWidget.header().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.treeWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Add or Remove Tags"))
        self.treeWidget.headerItem().setText(0, _translate("Form", "Analysis Steps"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Form", "Pre-Alignment"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("Form", "Adapters trimming"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("Form", "FASTQ read lenght filter"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("Form", "FASTQ quality filter"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("Form", "FASTQ quality control"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Form", "Alignment"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("Form", "UMI/Molecular barcodes merge"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("Form", "FASTQ alignment"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("Form", "SAM to BAM convertion"))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("Form", "BAM sort"))
        self.treeWidget.topLevelItem(1).child(4).setText(0, _translate("Form", "BAM quality control"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("Form", "Pre-Processing"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("Form", "BAM filter"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("Form", "Add readgroups to BAM"))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("Form", "PCR duplicates marking"))
        self.treeWidget.topLevelItem(2).child(3).setText(0, _translate("Form", "InDels realignment"))
        self.treeWidget.topLevelItem(2).child(4).setText(0, _translate("Form", "Base quality recalibration"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("Form", "Variant Calling"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("Form", "SNV & short InDels"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("Form", "Copy Number Variation"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("Form", "Post-Processing"))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("Form", "VCF filter"))
        self.treeWidget.topLevelItem(4).child(1).setText(0, _translate("Form", "Hard filter"))
        self.treeWidget.topLevelItem(4).child(2).setText(0, _translate("Form", "VCF to TSV convertion"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("Form", "Annotation"))
        self.treeWidget.topLevelItem(5).child(0).setText(0, _translate("Form", "SNV & short InDels"))
        self.treeWidget.topLevelItem(5).child(1).setText(0, _translate("Form", "Copy Number Variation"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
