# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jarvis/git/Powercall2/Powercall/Add_tool/add_tags.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_tool(object):
    def setupUi(self, Add_tool):
        Add_tool.setObjectName("Add_tool")
        Add_tool.resize(939, 798)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Add_tool.sizePolicy().hasHeightForWidth())
        Add_tool.setSizePolicy(sizePolicy)
        Add_tool.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.formLayout = QtWidgets.QFormLayout(Add_tool)
        self.formLayout.setObjectName("formLayout")
        self.frame = QtWidgets.QFrame(Add_tool)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.info_frame = QtWidgets.QFrame(self.frame)
        self.info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_frame.setObjectName("info_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.info_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.align_groupBox = QtWidgets.QGroupBox(self.info_frame)
        self.align_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.align_groupBox.setObjectName("align_groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.align_groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fastq_align_checkBox = QtWidgets.QCheckBox(self.align_groupBox)
        self.fastq_align_checkBox.setObjectName("fastq_align_checkBox")
        self.verticalLayout_3.addWidget(self.fastq_align_checkBox)
        self.samtobam_checkBox = QtWidgets.QCheckBox(self.align_groupBox)
        self.samtobam_checkBox.setObjectName("samtobam_checkBox")
        self.verticalLayout_3.addWidget(self.samtobam_checkBox)
        self.bam_sort_checkBox = QtWidgets.QCheckBox(self.align_groupBox)
        self.bam_sort_checkBox.setObjectName("bam_sort_checkBox")
        self.verticalLayout_3.addWidget(self.bam_sort_checkBox)
        self.bam_index_checkBox = QtWidgets.QCheckBox(self.align_groupBox)
        self.bam_index_checkBox.setObjectName("bam_index_checkBox")
        self.verticalLayout_3.addWidget(self.bam_index_checkBox)
        self.bam_QC_checkBox = QtWidgets.QCheckBox(self.align_groupBox)
        self.bam_QC_checkBox.setObjectName("bam_QC_checkBox")
        self.verticalLayout_3.addWidget(self.bam_QC_checkBox)
        self.gridLayout_2.addWidget(self.align_groupBox, 3, 2, 2, 1)
        self.pre_align_groupBox = QtWidgets.QGroupBox(self.info_frame)
        self.pre_align_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.pre_align_groupBox.setObjectName("pre_align_groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pre_align_groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.adap_trim_checkBox = QtWidgets.QCheckBox(self.pre_align_groupBox)
        self.adap_trim_checkBox.setObjectName("adap_trim_checkBox")
        self.verticalLayout_2.addWidget(self.adap_trim_checkBox)
        self.fastq_filter_checkBox = QtWidgets.QCheckBox(self.pre_align_groupBox)
        self.fastq_filter_checkBox.setObjectName("fastq_filter_checkBox")
        self.verticalLayout_2.addWidget(self.fastq_filter_checkBox)
        self.fastq_QC_checkBox = QtWidgets.QCheckBox(self.pre_align_groupBox)
        self.fastq_QC_checkBox.setObjectName("fastq_QC_checkBox")
        self.verticalLayout_2.addWidget(self.fastq_QC_checkBox)
        self.gridLayout_2.addWidget(self.pre_align_groupBox, 3, 1, 2, 1)
        self.pre_process_groupBox = QtWidgets.QGroupBox(self.info_frame)
        self.pre_process_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.pre_process_groupBox.setObjectName("pre_process_groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pre_process_groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.UMI_merge_checkBox = QtWidgets.QCheckBox(self.pre_process_groupBox)
        self.UMI_merge_checkBox.setObjectName("UMI_merge_checkBox")
        self.verticalLayout_4.addWidget(self.UMI_merge_checkBox)
        self.bam_filter_checkBox = QtWidgets.QCheckBox(self.pre_process_groupBox)
        self.bam_filter_checkBox.setObjectName("bam_filter_checkBox")
        self.verticalLayout_4.addWidget(self.bam_filter_checkBox)
        self.readgroups_checkBox = QtWidgets.QCheckBox(self.pre_process_groupBox)
        self.readgroups_checkBox.setObjectName("readgroups_checkBox")
        self.verticalLayout_4.addWidget(self.readgroups_checkBox)
        self.mark_dup_checkBox = QtWidgets.QCheckBox(self.pre_process_groupBox)
        self.mark_dup_checkBox.setObjectName("mark_dup_checkBox")
        self.verticalLayout_4.addWidget(self.mark_dup_checkBox)
        self.indel_real_checkBox = QtWidgets.QCheckBox(self.pre_process_groupBox)
        self.indel_real_checkBox.setObjectName("indel_real_checkBox")
        self.verticalLayout_4.addWidget(self.indel_real_checkBox)
        self.BQSR_checkBox = QtWidgets.QCheckBox(self.pre_process_groupBox)
        self.BQSR_checkBox.setObjectName("BQSR_checkBox")
        self.verticalLayout_4.addWidget(self.BQSR_checkBox)
        self.gridLayout_2.addWidget(self.pre_process_groupBox, 3, 3, 2, 1)
        self.VC_groupBox = QtWidgets.QGroupBox(self.info_frame)
        self.VC_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.VC_groupBox.setObjectName("VC_groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.VC_groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.VC_germline_checkBox = QtWidgets.QCheckBox(self.VC_groupBox)
        self.VC_germline_checkBox.setObjectName("VC_germline_checkBox")
        self.verticalLayout_5.addWidget(self.VC_germline_checkBox)
        self.VC_som_C_checkBox = QtWidgets.QCheckBox(self.VC_groupBox)
        self.VC_som_C_checkBox.setObjectName("VC_som_C_checkBox")
        self.verticalLayout_5.addWidget(self.VC_som_C_checkBox)
        self.VC_som_CC_checkBox = QtWidgets.QCheckBox(self.VC_groupBox)
        self.VC_som_CC_checkBox.setObjectName("VC_som_CC_checkBox")
        self.verticalLayout_5.addWidget(self.VC_som_CC_checkBox)
        self.VCF_QC_checkBox = QtWidgets.QCheckBox(self.VC_groupBox)
        self.VCF_QC_checkBox.setObjectName("VCF_QC_checkBox")
        self.verticalLayout_5.addWidget(self.VCF_QC_checkBox)
        self.gridLayout_2.addWidget(self.VC_groupBox, 5, 1, 1, 1)
        self.CNV_groupBox = QtWidgets.QGroupBox(self.info_frame)
        self.CNV_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.CNV_groupBox.setObjectName("CNV_groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.CNV_groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.CNV_call_checkBox = QtWidgets.QCheckBox(self.CNV_groupBox)
        self.CNV_call_checkBox.setObjectName("CNV_call_checkBox")
        self.verticalLayout_6.addWidget(self.CNV_call_checkBox)
        self.CNV_VCF_QC_checkBox = QtWidgets.QCheckBox(self.CNV_groupBox)
        self.CNV_VCF_QC_checkBox.setObjectName("CNV_VCF_QC_checkBox")
        self.verticalLayout_6.addWidget(self.CNV_VCF_QC_checkBox)
        self.gridLayout_2.addWidget(self.CNV_groupBox, 6, 1, 1, 1)
        self.post_processing_groupBox = QtWidgets.QGroupBox(self.info_frame)
        self.post_processing_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.post_processing_groupBox.setObjectName("post_processing_groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.post_processing_groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.VCF_filter_checkBox = QtWidgets.QCheckBox(self.post_processing_groupBox)
        self.VCF_filter_checkBox.setObjectName("VCF_filter_checkBox")
        self.verticalLayout_7.addWidget(self.VCF_filter_checkBox)
        self.VCF_merge_checkBox = QtWidgets.QCheckBox(self.post_processing_groupBox)
        self.VCF_merge_checkBox.setObjectName("VCF_merge_checkBox")
        self.verticalLayout_7.addWidget(self.VCF_merge_checkBox)
        self.VCF_norm_checkBox = QtWidgets.QCheckBox(self.post_processing_groupBox)
        self.VCF_norm_checkBox.setObjectName("VCF_norm_checkBox")
        self.verticalLayout_7.addWidget(self.VCF_norm_checkBox)
        self.VCFtoTSV_checkBox = QtWidgets.QCheckBox(self.post_processing_groupBox)
        self.VCFtoTSV_checkBox.setObjectName("VCFtoTSV_checkBox")
        self.verticalLayout_7.addWidget(self.VCFtoTSV_checkBox)
        self.gridLayout_2.addWidget(self.post_processing_groupBox, 5, 2, 2, 1)
        self.annotation_groupBox = QtWidgets.QGroupBox(self.info_frame)
        self.annotation_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.annotation_groupBox.setObjectName("annotation_groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.annotation_groupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.var_ann_checkBox = QtWidgets.QCheckBox(self.annotation_groupBox)
        self.var_ann_checkBox.setObjectName("var_ann_checkBox")
        self.verticalLayout_8.addWidget(self.var_ann_checkBox)
        self.CNV_ann_checkBox = QtWidgets.QCheckBox(self.annotation_groupBox)
        self.CNV_ann_checkBox.setObjectName("CNV_ann_checkBox")
        self.verticalLayout_8.addWidget(self.CNV_ann_checkBox)
        self.gridLayout_2.addWidget(self.annotation_groupBox, 5, 3, 2, 1)
        self.gridLayout.addWidget(self.info_frame, 4, 0, 1, 2)
        self.Save_pushButton = QtWidgets.QPushButton(self.frame)
        self.Save_pushButton.setObjectName("Save_pushButton")
        self.gridLayout.addWidget(self.Save_pushButton, 5, 1, 1, 1)
        self.Cancel_pushButton = QtWidgets.QPushButton(self.frame)
        self.Cancel_pushButton.setObjectName("Cancel_pushButton")
        self.gridLayout.addWidget(self.Cancel_pushButton, 5, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 2)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame)

        self.retranslateUi(Add_tool)
        QtCore.QMetaObject.connectSlotsByName(Add_tool)

    def retranslateUi(self, Add_tool):
        _translate = QtCore.QCoreApplication.translate
        Add_tool.setWindowTitle(_translate("Add_tool", "Add_tool"))
        self.align_groupBox.setTitle(_translate("Add_tool", "Alignment"))
        self.fastq_align_checkBox.setText(_translate("Add_tool", "Fastq Alignment"))
        self.samtobam_checkBox.setText(_translate("Add_tool", "Sam to Bam conversion"))
        self.bam_sort_checkBox.setText(_translate("Add_tool", "Sam/Bam Sorting"))
        self.bam_index_checkBox.setText(_translate("Add_tool", "Bam Indexing"))
        self.bam_QC_checkBox.setText(_translate("Add_tool", "Sam/Bam Quality Control"))
        self.pre_align_groupBox.setTitle(_translate("Add_tool", "Pre-Alignment"))
        self.adap_trim_checkBox.setText(_translate("Add_tool", "Adapters Trimming"))
        self.fastq_filter_checkBox.setText(_translate("Add_tool", "Fastq Filtering"))
        self.fastq_QC_checkBox.setText(_translate("Add_tool", "Fastq Quality Control"))
        self.pre_process_groupBox.setTitle(_translate("Add_tool", "Pre-Processing"))
        self.UMI_merge_checkBox.setText(_translate("Add_tool", "UMI merging"))
        self.bam_filter_checkBox.setText(_translate("Add_tool", "Bam filtering"))
        self.readgroups_checkBox.setText(_translate("Add_tool", "Modify ReadGroups"))
        self.mark_dup_checkBox.setText(_translate("Add_tool", "Duplicates Marking"))
        self.indel_real_checkBox.setText(_translate("Add_tool", "InDels Realignment"))
        self.BQSR_checkBox.setText(_translate("Add_tool", "BQSR"))
        self.VC_groupBox.setTitle(_translate("Add_tool", "Variant Calling(VC)"))
        self.VC_germline_checkBox.setText(_translate("Add_tool", "Germline VC"))
        self.VC_som_C_checkBox.setText(_translate("Add_tool", "Somatic VC - only Case"))
        self.VC_som_CC_checkBox.setText(_translate("Add_tool", "Somatic VC - Case-Control"))
        self.VCF_QC_checkBox.setText(_translate("Add_tool", "VCF Quality Control"))
        self.CNV_groupBox.setTitle(_translate("Add_tool", "CNV Calling"))
        self.CNV_call_checkBox.setText(_translate("Add_tool", "CNV Calling"))
        self.CNV_VCF_QC_checkBox.setText(_translate("Add_tool", "CNV VCF Quality Control"))
        self.post_processing_groupBox.setTitle(_translate("Add_tool", "Post-Processing"))
        self.VCF_filter_checkBox.setText(_translate("Add_tool", "VCF Filtering"))
        self.VCF_merge_checkBox.setText(_translate("Add_tool", "VCF Merging/Splitting"))
        self.VCF_norm_checkBox.setText(_translate("Add_tool", "VCF Normalization"))
        self.VCFtoTSV_checkBox.setText(_translate("Add_tool", "VCF to TSV/CSV conversion"))
        self.annotation_groupBox.setTitle(_translate("Add_tool", "Annotation"))
        self.var_ann_checkBox.setText(_translate("Add_tool", "Variants Annotation"))
        self.CNV_ann_checkBox.setText(_translate("Add_tool", "CNV Annotation"))
        self.Save_pushButton.setText(_translate("Add_tool", "Save"))
        self.Cancel_pushButton.setText(_translate("Add_tool", "Cancel"))
        self.label_5.setText(_translate("Add_tool", "Add Tags"))
