# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jarvis/git/Powercall2/Powercall/Add_tool/add_tool.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Add_tool(QtWidgets.QWidget):

    def __init__(self, parent = None):
        super(Add_tool, self).__init__(parent)
        self.setupUi()


    def setupUi(self):
        Add_tool.setObjectName("Add_tool")
        Add_tool.resize(800, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Add_tool.sizePolicy().hasHeightForWidth())
        Add_tool.setSizePolicy(sizePolicy)
        Add_tool.setMaximumSize(QtCore.QSize(800, 300))
        self.formLayout = QtWidgets.QFormLayout(Add_tool)
        self.formLayout.setObjectName("formLayout")
        self.frame = QtWidgets.QFrame(Add_tool)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 2)
        self.info_frame = QtWidgets.QFrame(self.frame)
        self.info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_frame.setObjectName("info_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.info_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.path_label = QtWidgets.QLabel(self.info_frame)
        self.path_label.setObjectName("path_label")
        self.gridLayout_2.addWidget(self.path_label, 2, 0, 1, 1)
        self.path_lineEdit = QtWidgets.QLineEdit(self.info_frame)
        self.path_lineEdit.setObjectName("path_lineEdit")
        self.gridLayout_2.addWidget(self.path_lineEdit, 2, 1, 1, 3)
        self.tags_label = QtWidgets.QLabel(self.info_frame)
        self.tags_label.setObjectName("tags_label")
        self.gridLayout_2.addWidget(self.tags_label, 3, 0, 1, 1)
        self.version_label = QtWidgets.QLabel(self.info_frame)
        self.version_label.setObjectName("version_label")
        self.gridLayout_2.addWidget(self.version_label, 1, 0, 1, 1)
        self.version_lineEdit = QtWidgets.QLineEdit(self.info_frame)
        self.version_lineEdit.setObjectName("version_lineEdit")
        self.gridLayout_2.addWidget(self.version_lineEdit, 1, 1, 1, 3)
        self.pathSearch_toolButton = QtWidgets.QToolButton(self.info_frame)
        self.pathSearch_toolButton.setObjectName("pathSearch_toolButton")
        self.gridLayout_2.addWidget(self.pathSearch_toolButton, 2, 4, 1, 1)
        self.tags_lineEdit = QtWidgets.QLineEdit(self.info_frame)
        self.tags_lineEdit.setObjectName("tags_lineEdit")
        self.gridLayout_2.addWidget(self.tags_lineEdit, 3, 1, 1, 3)
        self.addTags_pushButton = QtWidgets.QPushButton(self.info_frame)
        self.addTags_pushButton.setObjectName("addTags_pushButton")
        self.gridLayout_2.addWidget(self.addTags_pushButton, 3, 4, 1, 1)
        self.toolname_label = QtWidgets.QLabel(self.info_frame)
        self.toolname_label.setObjectName("toolname_label")
        self.gridLayout_2.addWidget(self.toolname_label, 0, 0, 1, 1)
        self.toolname_lineEdit = QtWidgets.QLineEdit(self.info_frame)
        self.toolname_lineEdit.setObjectName("toolname_lineEdit")
        self.gridLayout_2.addWidget(self.toolname_lineEdit, 0, 1, 1, 3)
        self.gridLayout.addWidget(self.info_frame, 4, 0, 1, 2)
        self.Save_pushButton = QtWidgets.QPushButton(self.frame)
        self.Save_pushButton.setObjectName("Save_pushButton")
        self.gridLayout.addWidget(self.Save_pushButton, 5, 1, 1, 1)
        self.Cancel_pushButton = QtWidgets.QPushButton(self.frame)
        self.Cancel_pushButton.setObjectName("Cancel_pushButton")
        self.gridLayout.addWidget(self.Cancel_pushButton, 5, 0, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame)

        self.retranslateUi(Add_tool)
        QtCore.QMetaObject.connectSlotsByName(Add_tool)

    def retranslateUi(self, Add_tool):
        _translate = QtCore.QCoreApplication.translate
        Add_tool.setWindowTitle(_translate("Add_tool", "Add_tool"))
        self.label_5.setText(_translate("Add_tool", "Add Tool INFO"))
        self.path_label.setText(_translate("Add_tool", "Path:"))
        self.tags_label.setText(_translate("Add_tool", "Tags:"))
        self.version_label.setText(_translate("Add_tool", "Version:"))
        self.pathSearch_toolButton.setText(_translate("Add_tool", "Search..."))
        self.addTags_pushButton.setText(_translate("Add_tool", "Add Tags"))
        self.toolname_label.setText(_translate("Add_tool", "Tool Name:"))
        self.Save_pushButton.setText(_translate("Add_tool", "Save"))
        self.Cancel_pushButton.setText(_translate("Add_tool", "Cancel"))
