# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jarvis/git/Powercall2/Powercall/pipeline_designer.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pipeline_page(object):
    def setupUi(self, Pipeline_page):
        Pipeline_page.setObjectName("Pipeline_page")
        Pipeline_page.resize(1017, 890)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Pipeline_page.sizePolicy().hasHeightForWidth())
        Pipeline_page.setSizePolicy(sizePolicy)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Pipeline_page)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mframe = QtWidgets.QFrame(Pipeline_page)
        self.mframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mframe.setObjectName("mframe")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mframe)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.mframe)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.radioButton = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_3.addWidget(self.radioButton)
        self.listWidget = QtWidgets.QListWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate)
        self.listWidget.addItem(item)
        self.verticalLayout_3.addWidget(self.listWidget)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.textBrowser.setDocumentTitle("")
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(32)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.gridLayout_2.addWidget(self.frame_2, 1, 1, 2, 1)
        self.frame_3 = QtWidgets.QFrame(self.mframe)
        self.frame_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayout = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setContentsMargins(9, -1, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.frame_3)
        self.treeWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(461, 548))
        self.treeWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treeWidget.setAcceptDrops(False)
        self.treeWidget.setAutoFillBackground(True)
        self.treeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.treeWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.treeWidget.setAutoExpandDelay(-1)
        self.treeWidget.setIndentation(20)
        self.treeWidget.setRootIsDecorated(True)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setAllColumnsShowFocus(False)
        self.treeWidget.setHeaderHidden(False)
        self.treeWidget.setColumnCount(2)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setCascadingSectionResizes(True)
        self.treeWidget.header().setDefaultSectionSize(300)
        self.treeWidget.header().setHighlightSections(False)
        self.treeWidget.header().setMinimumSectionSize(100)
        self.treeWidget.header().setSortIndicatorShown(False)
        self.treeWidget.header().setStretchLastSection(True)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.treeWidget)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_2.sizePolicy().hasHeightForWidth())
        self.textBrowser_2.setSizePolicy(sizePolicy)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.textBrowser_2)
        self.gridLayout_2.addWidget(self.frame_3, 1, 0, 2, 1)
        self.frame_4 = QtWidgets.QFrame(self.mframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 0, 9, 1, 3)
        self.toolButton = QtWidgets.QToolButton(self.frame_4)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 3, 2, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 11, 1, 1)
        self.Pipeline_name = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Pipeline_name.sizePolicy().hasHeightForWidth())
        self.Pipeline_name.setSizePolicy(sizePolicy)
        self.Pipeline_name.setObjectName("Pipeline_name")
        self.gridLayout.addWidget(self.Pipeline_name, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 3, 10, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 8, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 8, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 3)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 3, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 9, 1, 1)
        self.gridLayout_2.addWidget(self.frame_4, 0, 0, 1, 2)
        self.horizontalLayout_2.addWidget(self.mframe)

        self.retranslateUi(Pipeline_page)
        QtCore.QMetaObject.connectSlotsByName(Pipeline_page)

    def retranslateUi(self, Pipeline_page):
        _translate = QtCore.QCoreApplication.translate
        Pipeline_page.setWindowTitle(_translate("Pipeline_page", "Analysis Settings"))
        self.label.setText(_translate("Pipeline_page", "TextLabel"))
        self.radioButton.setText(_translate("Pipeline_page", "RadioButton"))
        self.listWidget.setSortingEnabled(True)
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Pipeline_page", "New Item"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Pipeline_page", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Pipeline_page", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Pipeline_page", "New Column"))
        self.treeWidget.headerItem().setText(0, _translate("Pipeline_page", "Analysis Steps"))
        self.treeWidget.headerItem().setText(1, _translate("Pipeline_page", "Tools"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Pipeline_page", "Pre-Alignment"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("Pipeline_page", "Adapters trimming"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("Pipeline_page", "FASTQ read lenght filter"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("Pipeline_page", "FASTQ quality filter"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("Pipeline_page", "FASTQ quality control"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Pipeline_page", "Alignment"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("Pipeline_page", "UMI/Molecular barcodes merge"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("Pipeline_page", "FASTQ alignment"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("Pipeline_page", "SAM to BAM convertion"))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("Pipeline_page", "BAM sort"))
        self.treeWidget.topLevelItem(1).child(4).setText(0, _translate("Pipeline_page", "BAM quality control"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("Pipeline_page", "Pre-Processing"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("Pipeline_page", "BAM filter"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("Pipeline_page", "Add readgroups to BAM"))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("Pipeline_page", "PCR duplicates marking"))
        self.treeWidget.topLevelItem(2).child(3).setText(0, _translate("Pipeline_page", "InDels realignment"))
        self.treeWidget.topLevelItem(2).child(4).setText(0, _translate("Pipeline_page", "Base quality recalibration"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("Pipeline_page", "Variant Calling"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("Pipeline_page", "SNV & short InDels"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("Pipeline_page", "Copy Number Variation"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("Pipeline_page", "Post-Processing"))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("Pipeline_page", "VCF filter"))
        self.treeWidget.topLevelItem(4).child(1).setText(0, _translate("Pipeline_page", "Hard filter"))
        self.treeWidget.topLevelItem(4).child(2).setText(0, _translate("Pipeline_page", "VCF to TSV convertion"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("Pipeline_page", "Annotation"))
        self.treeWidget.topLevelItem(5).child(0).setText(0, _translate("Pipeline_page", "SNV & short InDels"))
        self.treeWidget.topLevelItem(5).child(1).setText(0, _translate("Pipeline_page", "Copy Number Variation"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.toolButton.setText(_translate("Pipeline_page", "..."))
        self.pushButton.setText(_translate("Pipeline_page", "Save"))
        self.Pipeline_name.setText(_translate("Pipeline_page", "Pipeline:"))
        self.pushButton_3.setText(_translate("Pipeline_page", "Cancel"))
        self.label_3.setText(_translate("Pipeline_page", "Tools cfg:"))
        self.label_2.setText(_translate("Pipeline_page", "Reference version:"))
        self.pushButton_2.setText(_translate("Pipeline_page", "Reset"))
