# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jarvis/git/Powercall2/Powercall/tool_settings.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Analysis_page(object):
    def setupUi(self, Analysis_page):
        Analysis_page.setObjectName("Analysis_page")
        Analysis_page.resize(1177, 890)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Analysis_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(Analysis_page)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.frame)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tool_groupBox = QtWidgets.QGroupBox(self.splitter)
        self.tool_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.tool_groupBox.setObjectName("tool_groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tool_groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.deleteTool_pushButton = QtWidgets.QPushButton(self.tool_groupBox)
        self.deleteTool_pushButton.setObjectName("deleteTool_pushButton")
        self.gridLayout_5.addWidget(self.deleteTool_pushButton, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 0, 1, 1)
        self.tool_listWidget = QtWidgets.QListWidget(self.tool_groupBox)
        self.tool_listWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tool_listWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tool_listWidget.setMidLineWidth(1)
        self.tool_listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tool_listWidget.setObjectName("tool_listWidget")
        self.gridLayout_5.addWidget(self.tool_listWidget, 2, 0, 1, 3)
        self.addtool_pushButton = QtWidgets.QPushButton(self.tool_groupBox)
        self.addtool_pushButton.setObjectName("addtool_pushButton")
        self.gridLayout_5.addWidget(self.addtool_pushButton, 0, 1, 1, 1)
        self.DB_groupBox = QtWidgets.QGroupBox(self.splitter)
        self.DB_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.DB_groupBox.setObjectName("DB_groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.DB_groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.deleteDB_pushButton = QtWidgets.QPushButton(self.DB_groupBox)
        self.deleteDB_pushButton.setObjectName("deleteDB_pushButton")
        self.gridLayout.addWidget(self.deleteDB_pushButton, 0, 2, 1, 1)
        self.addDB_pushButton = QtWidgets.QPushButton(self.DB_groupBox)
        self.addDB_pushButton.setObjectName("addDB_pushButton")
        self.gridLayout.addWidget(self.addDB_pushButton, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.DB_listWidget = QtWidgets.QListWidget(self.DB_groupBox)
        self.DB_listWidget.setObjectName("DB_listWidget")
        self.gridLayout.addWidget(self.DB_listWidget, 1, 0, 1, 3)
        self.ref_groupBox = QtWidgets.QGroupBox(self.splitter)
        self.ref_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ref_groupBox.setObjectName("ref_groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.ref_groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.deleteRef_pushButton = QtWidgets.QPushButton(self.ref_groupBox)
        self.deleteRef_pushButton.setObjectName("deleteRef_pushButton")
        self.gridLayout_4.addWidget(self.deleteRef_pushButton, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 0, 1, 1)
        self.addRef_pushButton = QtWidgets.QPushButton(self.ref_groupBox)
        self.addRef_pushButton.setObjectName("addRef_pushButton")
        self.gridLayout_4.addWidget(self.addRef_pushButton, 0, 1, 1, 1)
        self.ref_listWidget = QtWidgets.QListWidget(self.ref_groupBox)
        self.ref_listWidget.setObjectName("ref_listWidget")
        self.gridLayout_4.addWidget(self.ref_listWidget, 1, 0, 1, 3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.gridLayout_6.addWidget(self.tableWidget, 2, 0, 1, 2)
        self.changeSetting_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.changeSetting_pushButton.setObjectName("changeSetting_pushButton")
        self.gridLayout_6.addWidget(self.changeSetting_pushButton, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.splitter_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(Analysis_page)
        QtCore.QMetaObject.connectSlotsByName(Analysis_page)

    def retranslateUi(self, Analysis_page):
        _translate = QtCore.QCoreApplication.translate
        Analysis_page.setWindowTitle(_translate("Analysis_page", "Analysis Settings"))
        self.tool_groupBox.setTitle(_translate("Analysis_page", "Tools"))
        self.deleteTool_pushButton.setText(_translate("Analysis_page", "Delete"))
        self.addtool_pushButton.setText(_translate("Analysis_page", "Add"))
        self.DB_groupBox.setTitle(_translate("Analysis_page", "Databases"))
        self.deleteDB_pushButton.setText(_translate("Analysis_page", "Delete"))
        self.addDB_pushButton.setText(_translate("Analysis_page", "Add"))
        self.ref_groupBox.setTitle(_translate("Analysis_page", "Reference genomes"))
        self.deleteRef_pushButton.setText(_translate("Analysis_page", "Delete"))
        self.addRef_pushButton.setText(_translate("Analysis_page", "Add"))
        #self.groupBox_2.setTitle(_translate("Analysis_page", "Settings"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Analysis_page", "aasdasd"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Analysis_page", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Analysis_page", "New Column"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Analysis_page", "ciaoassssssssssssssssssssssssssssssssssssssssssssssssssssssss"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.changeSetting_pushButton.setText(_translate("Analysis_page", "Change settings"))
        self.label.setText(_translate("Analysis_page", "Tools Settings"))
