# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jarvis/git/Powercall2/Powercall/Add_tool/add_tool.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Add_tool(QtWidgets.QWidget):

    def __init__(self, parent = None):
        super(Add_tool, self).__init__(parent)
        self.setupUi()


    def setupUi(self):

        self.setObjectName("Add_tool")
        self.resize(800, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMaximumSize(QtCore.QSize(800, 300))
        self.formLayout = QtWidgets.QFormLayout(self)
        self.formLayout.setObjectName("formLayout")
        self.frame = QtWidgets.QFrame(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 2)
        self.info_frame = QtWidgets.QFrame(self.frame)
        self.info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_frame.setObjectName("info_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.info_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.path_label = QtWidgets.QLabel(self.info_frame)
        self.path_label.setObjectName("path_label")
        self.gridLayout_2.addWidget(self.path_label, 2, 0, 1, 1)
        self.path_lineEdit = QtWidgets.QLineEdit(self.info_frame)
        self.path_lineEdit.setObjectName("path_lineEdit")
        self.gridLayout_2.addWidget(self.path_lineEdit, 2, 1, 1, 3)
        self.tags_label = QtWidgets.QLabel(self.info_frame)
        self.tags_label.setObjectName("tags_label")
        self.gridLayout_2.addWidget(self.tags_label, 3, 0, 1, 1)
        self.version_label = QtWidgets.QLabel(self.info_frame)
        self.version_label.setObjectName("version_label")
        self.gridLayout_2.addWidget(self.version_label, 1, 0, 1, 1)
        self.version_lineEdit = QtWidgets.QLineEdit(self.info_frame)
        self.version_lineEdit.setObjectName("version_lineEdit")
        self.gridLayout_2.addWidget(self.version_lineEdit, 1, 1, 1, 3)
        self.pathSearch_toolButton = QtWidgets.QToolButton(self.info_frame)
        self.pathSearch_toolButton.setObjectName("pathSearch_toolButton")
        self.gridLayout_2.addWidget(self.pathSearch_toolButton, 2, 4, 1, 1)
        self.tags_lineEdit = QtWidgets.QLineEdit(self.info_frame)
        self.tags_lineEdit.setObjectName("tags_lineEdit")
        self.gridLayout_2.addWidget(self.tags_lineEdit, 3, 1, 1, 3)
        self.addTags_pushButton = QtWidgets.QPushButton(self.info_frame)
        self.addTags_pushButton.setObjectName("addTags_pushButton")
        self.gridLayout_2.addWidget(self.addTags_pushButton, 3, 4, 1, 1)
        self.toolname_label = QtWidgets.QLabel(self.info_frame)
        self.toolname_label.setObjectName("toolname_label")
        self.gridLayout_2.addWidget(self.toolname_label, 0, 0, 1, 1)
        self.toolname_lineEdit = QtWidgets.QLineEdit(self.info_frame)
        self.toolname_lineEdit.setObjectName("toolname_lineEdit")
        self.gridLayout_2.addWidget(self.toolname_lineEdit, 0, 1, 1, 3)
        self.gridLayout.addWidget(self.info_frame, 4, 0, 1, 2)
        self.Save_pushButton = QtWidgets.QPushButton(self.frame)
        self.Save_pushButton.setObjectName("Save_pushButton")
        self.gridLayout.addWidget(self.Save_pushButton, 5, 1, 1, 1)
        self.Cancel_pushButton = QtWidgets.QPushButton(self.frame)
        self.Cancel_pushButton.setObjectName("Cancel_pushButton")
        self.gridLayout.addWidget(self.Cancel_pushButton, 5, 0, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Add_tool):
        _translate = QtCore.QCoreApplication.translate
        Add_tool.setWindowTitle(_translate("Add_tool", "Add new tool"))
        self.label_5.setText(_translate("Add_tool", "Add Tool INFO"))
        self.path_label.setText(_translate("Add_tool", "Tool Path:"))
        self.tags_label.setText(_translate("Add_tool", "Tags:"))
        self.version_label.setText(_translate("Add_tool", "Tool Version:"))
        self.pathSearch_toolButton.setText(_translate("Add_tool", "Search..."))
        self.addTags_pushButton.setText(_translate("Add_tool", "Add Tags"))
        self.toolname_label.setText(_translate("Add_tool", "Tool Name:"))
        self.Save_pushButton.setText(_translate("Add_tool", "Save"))
        self.Cancel_pushButton.setText(_translate("Add_tool", "Cancel"))


    def save_tool_infos(self):

        self.tool_name = self.toolname_lineEdit.text()
        #self.version = self.toolname_lineEdit.text()
        #sprint('salvatoooo')




class Add_tags(QtWidgets.QWidget):


    def __init__(self, parent = None):
        super(Add_tags, self).__init__(parent)
        self.setupUi()


    def setupUi(self):
        self.setObjectName("Add_tags")
        self.resize(639, 683)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.treeWidget = QtWidgets.QTreeWidget(self.frame)
        self.treeWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(461, 548))
        self.treeWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treeWidget.setAcceptDrops(False)
        self.treeWidget.setAutoFillBackground(True)
        self.treeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.treeWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.treeWidget.setAutoExpandDelay(-1)
        self.treeWidget.setIndentation(20)
        self.treeWidget.setRootIsDecorated(True)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setAllColumnsShowFocus(False)
        self.treeWidget.setHeaderHidden(False)
        self.treeWidget.setColumnCount(1)
        self.treeWidget.setObjectName("treeWidget")

        self.item_pre_alig = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.item_pre_alig.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate|self.item_pre_alig.flags())
        self.item_adapt = QtWidgets.QTreeWidgetItem(self.item_pre_alig)
        self.item_adapt.setFlags(self.item_adapt.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_adapt.setCheckState(0, QtCore.Qt.Unchecked)
        self.item_len_filt = QtWidgets.QTreeWidgetItem(self.item_pre_alig)
        self.item_len_filt.setFlags(self.item_len_filt.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_len_filt.setCheckState(0, QtCore.Qt.Unchecked)
        self.item_q_filt = QtWidgets.QTreeWidgetItem(self.item_pre_alig)
        self.item_q_filt.setFlags(self.item_q_filt.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_q_filt.setCheckState(0, QtCore.Qt.Unchecked)
        self.item_fq_qc = QtWidgets.QTreeWidgetItem(self.item_pre_alig)
        self.item_fq_qc.setFlags(self.item_fq_qc.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_fq_qc.setCheckState(0, QtCore.Qt.Unchecked)

        self.item_align = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.item_align.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate|self.item_align.flags())      
        self.item_umi = QtWidgets.QTreeWidgetItem(self.item_align)
        self.item_umi.setFlags(self.item_umi.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_umi.setCheckState(0, QtCore.Qt.Unchecked)
        self.item_alig = QtWidgets.QTreeWidgetItem(self.item_align)
        self.item_alig.setFlags(self.item_alig.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_alig.setCheckState(0, QtCore.Qt.Unchecked)
        self.item_sambam = QtWidgets.QTreeWidgetItem(self.item_align)
        self.item_sambam.setFlags(self.item_sambam.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_sambam.setCheckState(0, QtCore.Qt.Unchecked)
        self.item_sort = QtWidgets.QTreeWidgetItem(self.item_align)
        self.item_sort.setFlags(self.item_sort.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_sort.setCheckState(0, QtCore.Qt.Unchecked)
        self.item_bam_qc = QtWidgets.QTreeWidgetItem(self.item_align)
        self.item_bam_qc.setFlags(self.item_bam_qc.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_bam_qc.setCheckState(0, QtCore.Qt.Unchecked)

        self.item_pre_proc = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.item_pre_proc.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate|self.item_pre_proc.flags())      
       
        self.item_bam_filt = QtWidgets.QTreeWidgetItem(self.item_pre_proc)
        self.item_bam_filt.setFlags(self.item_bam_qc.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_bam_filt.setCheckState(0, QtCore.Qt.Unchecked)
        self.item_rgroup = QtWidgets.QTreeWidgetItem(self.item_pre_proc)
        self.item_rgroup.setFlags(self.item_rgroup.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_rgroup.setCheckState(0, QtCore.Qt.Unchecked)
        self.item_dup = QtWidgets.QTreeWidgetItem(self.item_pre_proc)
        self.item_dup.setFlags(self.item_dup.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_dup.setCheckState(0, QtCore.Qt.Unchecked)
        self.item_realig = QtWidgets.QTreeWidgetItem(self.item_pre_proc)
        self.item_realig.setFlags(self.item_realig.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_realig.setCheckState(0, QtCore.Qt.Unchecked)
        self.item_bqsr = QtWidgets.QTreeWidgetItem(self.item_pre_proc)
        self.item_bqsr.setFlags(self.item_bqsr.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_bqsr.setCheckState(0, QtCore.Qt.Unchecked)

        self.item_vcalling = QtWidgets.QTreeWidgetItem(self.treeWidget)     
        self.item_vcalling.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate|self.item_vcalling.flags())      
    
        self.item_shortv_call = QtWidgets.QTreeWidgetItem(self.item_vcalling)
        self.item_shortv_call.setFlags(self.item_shortv_call.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_shortv_call.setCheckState(0, QtCore.Qt.Unchecked)
        self.item_cnv_call = QtWidgets.QTreeWidgetItem(self.item_vcalling)
        self.item_cnv_call.setFlags(self.item_cnv_call.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_cnv_call.setCheckState(0, QtCore.Qt.Unchecked)

        self.item_post_proc = QtWidgets.QTreeWidgetItem(self.treeWidget)     
        self.item_post_proc.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate|self.item_post_proc.flags())      
    
        self.item_vcf_norm = QtWidgets.QTreeWidgetItem(self.item_post_proc)
        self.item_vcf_norm.setFlags(self.item_vcf_norm.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_vcf_norm.setCheckState(0, QtCore.Qt.Unchecked)
        self.item_vcf_filt = QtWidgets.QTreeWidgetItem(self.item_post_proc)
        self.item_vcf_filt.setFlags(self.item_vcf_filt.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_vcf_filt.setCheckState(0, QtCore.Qt.Unchecked)
        self.item_vcf_to_tsv = QtWidgets.QTreeWidgetItem(self.item_post_proc)
        self.item_vcf_to_tsv.setFlags(self.item_vcf_to_tsv.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_vcf_to_tsv.setCheckState(0, QtCore.Qt.Unchecked)

        self.item_ann = QtWidgets.QTreeWidgetItem(self.treeWidget)     
        self.item_ann.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate|self.item_ann.flags())      
    
        self.item_shortv_ann = QtWidgets.QTreeWidgetItem(self.item_ann)
        self.item_shortv_ann.setFlags(self.item_shortv_ann.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_shortv_ann.setCheckState(0, QtCore.Qt.Unchecked)
        self.item_cnv_ann = QtWidgets.QTreeWidgetItem(self.item_ann)
        self.item_cnv_ann.setFlags(self.item_cnv_ann.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_cnv_ann.setCheckState(0, QtCore.Qt.Unchecked)

        self.item_postann = QtWidgets.QTreeWidgetItem(self.treeWidget)     
        self.item_postann.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate|self.item_postann.flags())      
        
        self.item_filt_ann = QtWidgets.QTreeWidgetItem(self.item_postann)
        self.item_filt_ann.setFlags(self.item_filt_ann.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_filt_ann.setCheckState(0, QtCore.Qt.Unchecked)
        self.item_trs_filt_ann = QtWidgets.QTreeWidgetItem(self.item_postann)
        self.item_trs_filt_ann.setFlags(self.item_trs_filt_ann.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_trs_filt_ann.setCheckState(0, QtCore.Qt.Unchecked)
        self.item_vcf_ann_to_tsv = QtWidgets.QTreeWidgetItem(self.item_postann)
        self.item_vcf_ann_to_tsv.setFlags(self.item_cnv_ann.flags() | QtCore.Qt.ItemIsUserCheckable)
        self.item_vcf_ann_to_tsv.setCheckState(0, QtCore.Qt.Unchecked)

        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setCascadingSectionResizes(True)
        self.treeWidget.header().setDefaultSectionSize(300)
        self.treeWidget.header().setHighlightSections(False)
        self.treeWidget.header().setMinimumSectionSize(100)
        self.treeWidget.header().setSortIndicatorShown(False)
        self.treeWidget.header().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.treeWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Add_tags", "Add_tags"))
        self.label.setText(_translate("Add_tags", "Add or Remove Tags"))
        self.treeWidget.headerItem().setText(0, _translate("Add_tags", "Analysis Steps"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Add_tags", "Pre-Alignment"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("Add_tags", "Adapters trimming"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("Add_tags", "FASTQ read lenght filter"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("Add_tags", "FASTQ quality filter"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("Add_tags", "FASTQ quality control"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Add_tags", "Alignment"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("Add_tags", "UMI/Molecular barcodes merge"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("Add_tags", "FASTQ alignment"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("Add_tags", "SAM to BAM convertion"))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("Add_tags", "BAM sort"))
        self.treeWidget.topLevelItem(1).child(4).setText(0, _translate("Add_tags", "BAM quality control"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("Add_tags", "Pre-Processing"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("Add_tags", "BAM filter"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("Add_tags", "Add readgroups to BAM"))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("Add_tags", "PCR duplicates marking"))
        self.treeWidget.topLevelItem(2).child(3).setText(0, _translate("Add_tags", "InDels realignment"))
        self.treeWidget.topLevelItem(2).child(4).setText(0, _translate("Add_tags", "Base quality recalibration"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("Add_tags", "Variant Calling"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("Add_tags", "SNV & short InDels"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("Add_tags", "Copy Number Variation"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("Add_tags", "Post-Processing"))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("Add_tags", "VCF filter"))
        self.treeWidget.topLevelItem(4).child(1).setText(0, _translate("Add_tags", "Hard filter"))
        self.treeWidget.topLevelItem(4).child(2).setText(0, _translate("Add_tags", "VCF to TSV convertion"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("Add_tags", "Annotation"))
        self.treeWidget.topLevelItem(5).child(0).setText(0, _translate("Add_tags", "SNV & short InDels"))
        self.treeWidget.topLevelItem(5).child(1).setText(0, _translate("Add_tags", "Copy Number Variation"))    
        self.treeWidget.topLevelItem(6).setText(0, _translate("Add_tags", "Post-Annotation"))
        self.treeWidget.topLevelItem(6).child(0).setText(0, _translate("Add_tags", "Annotation filter"))
        self.treeWidget.topLevelItem(6).child(2).setText(0, _translate("Add_tags", "Annotated VCF to TSV convertion"))
        self.treeWidget.topLevelItem(6).child(1).setText(0, _translate("Add_tags", "Ann transcripts filter"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)


class Add_DB(QtWidgets.QWidget):

    def __init__(self, parent = None):
        super(Add_DB, self).__init__(parent)
        self.setupUi()


    def setupUi(self):

        self.setObjectName("Add_DB")
        self.resize(800, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMaximumSize(QtCore.QSize(800, 300))
        self.formLayout = QtWidgets.QFormLayout(self)
        self.formLayout.setObjectName("formLayout")
        self.frame = QtWidgets.QFrame(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 2)
        self.info_frame = QtWidgets.QFrame(self.frame)
        self.info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_frame.setObjectName("info_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.info_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.path_label = QtWidgets.QLabel(self.info_frame)
        self.path_label.setObjectName("path_label")
        self.gridLayout_2.addWidget(self.path_label, 2, 0, 1, 1)
        self.path_lineEdit = QtWidgets.QLineEdit(self.info_frame)
        self.path_lineEdit.setObjectName("path_lineEdit")
        self.gridLayout_2.addWidget(self.path_lineEdit, 2, 1, 1, 3)
        self.version_label = QtWidgets.QLabel(self.info_frame)
        self.version_label.setObjectName("version_label")
        self.gridLayout_2.addWidget(self.version_label, 1, 0, 1, 1)
        self.version_lineEdit = QtWidgets.QLineEdit(self.info_frame)
        self.version_lineEdit.setObjectName("version_lineEdit")
        self.gridLayout_2.addWidget(self.version_lineEdit, 1, 1, 1, 3)
        self.pathSearch_toolButton = QtWidgets.QToolButton(self.info_frame)
        self.pathSearch_toolButton.setObjectName("pathSearch_toolButton")
        self.gridLayout_2.addWidget(self.pathSearch_toolButton, 2, 4, 1, 1)
        self.DBname_label = QtWidgets.QLabel(self.info_frame)
        self.DBname_label.setObjectName("DBname_label")
        self.gridLayout_2.addWidget(self.DBname_label, 0, 0, 1, 1)
        self.DBname_lineEdit = QtWidgets.QLineEdit(self.info_frame)
        self.DBname_lineEdit.setObjectName("DBname_lineEdit")
        self.gridLayout_2.addWidget(self.DBname_lineEdit, 0, 1, 1, 3)
        self.gridLayout.addWidget(self.info_frame, 4, 0, 1, 2)
        self.Save_pushButton = QtWidgets.QPushButton(self.frame)
        self.Save_pushButton.setObjectName("Save_pushButton")
        self.gridLayout.addWidget(self.Save_pushButton, 5, 1, 1, 1)
        self.Cancel_pushButton = QtWidgets.QPushButton(self.frame)
        self.Cancel_pushButton.setObjectName("Cancel_pushButton")
        self.gridLayout.addWidget(self.Cancel_pushButton, 5, 0, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Add_DB):
        _translate = QtCore.QCoreApplication.translate
        Add_DB.setWindowTitle(_translate("Add_DB", "Add_DataBase"))
        self.label_5.setText(_translate("Add_DB", "Add DB INFO"))
        self.path_label.setText(_translate("Add_DB", "DB Path:"))
        self.version_label.setText(_translate("Add_DB", "DB Version:"))
        self.pathSearch_toolButton.setText(_translate("Add_DB", "Search..."))
        self.DBname_label.setText(_translate("Add_DB", "DB Name:"))
        self.Save_pushButton.setText(_translate("Add_DB", "Save"))
        self.Cancel_pushButton.setText(_translate("Add_DB", "Cancel"))


    def save_tool_infos(self):

        self.tool_name = self.toolname_lineEdit.text()
        #self.version = self.toolname_lineEdit.text()
        print('salvatoooo')


class Add_Ref(QtWidgets.QWidget):

    def __init__(self, parent = None):
        super(Add_Ref, self).__init__(parent)
        self.setupUi()


    def setupUi(self):

        self.setObjectName("Add_Ref")
        self.resize(800, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMaximumSize(QtCore.QSize(800, 300))
        self.formLayout = QtWidgets.QFormLayout(self)
        self.formLayout.setObjectName("formLayout")
        self.frame = QtWidgets.QFrame(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 2)
        self.info_frame = QtWidgets.QFrame(self.frame)
        self.info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_frame.setObjectName("info_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.info_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.path_label = QtWidgets.QLabel(self.info_frame)
        self.path_label.setObjectName("path_label")
        self.gridLayout_2.addWidget(self.path_label, 2, 0, 1, 1)
        self.path_lineEdit = QtWidgets.QLineEdit(self.info_frame)
        self.path_lineEdit.setObjectName("path_lineEdit")
        self.gridLayout_2.addWidget(self.path_lineEdit, 2, 1, 1, 3)
        self.version_label = QtWidgets.QLabel(self.info_frame)
        self.version_label.setObjectName("version_label")
        self.gridLayout_2.addWidget(self.version_label, 1, 0, 1, 1)
        self.version_lineEdit = QtWidgets.QLineEdit(self.info_frame)
        self.version_lineEdit.setObjectName("version_lineEdit")
        self.gridLayout_2.addWidget(self.version_lineEdit, 1, 1, 1, 3)
        self.pathSearch_toolButton = QtWidgets.QToolButton(self.info_frame)
        self.pathSearch_toolButton.setObjectName("pathSearch_toolButton")
        self.gridLayout_2.addWidget(self.pathSearch_toolButton, 2, 4, 1, 1)
        self.Refname_label = QtWidgets.QLabel(self.info_frame)
        self.Refname_label.setObjectName("Refname_label")
        self.gridLayout_2.addWidget(self.Refname_label, 0, 0, 1, 1)
        self.Refname_lineEdit = QtWidgets.QLineEdit(self.info_frame)
        self.Refname_lineEdit.setObjectName("Refname_lineEdit")
        self.gridLayout_2.addWidget(self.Refname_lineEdit, 0, 1, 1, 3)
        self.gridLayout.addWidget(self.info_frame, 4, 0, 1, 2)
        self.Save_pushButton = QtWidgets.QPushButton(self.frame)
        self.Save_pushButton.setObjectName("Save_pushButton")
        self.gridLayout.addWidget(self.Save_pushButton, 5, 1, 1, 1)
        self.Cancel_pushButton = QtWidgets.QPushButton(self.frame)
        self.Cancel_pushButton.setObjectName("Cancel_pushButton")
        self.gridLayout.addWidget(self.Cancel_pushButton, 5, 0, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)
        self.ref_dict = ''

    def retranslateUi(self, Add_Ref):
        _translate = QtCore.QCoreApplication.translate
        Add_Ref.setWindowTitle(_translate("Add_Ref", "Add_reference"))
        self.label_5.setText(_translate("Add_Ref", "Add Reference genome INFO"))
        self.path_label.setText(_translate("Add_Ref", "Fasta file path:"))
        self.version_label.setText(_translate("Add_Ref", "Version:"))
        self.pathSearch_toolButton.setText(_translate("Add_Ref", "Search..."))
        self.Refname_label.setText(_translate("Add_Ref", "Reference Name:"))
        self.Save_pushButton.setText(_translate("Add_Ref", "Save"))
        self.Cancel_pushButton.setText(_translate("Add_Ref", "Cancel"))


class Add_Info(QtWidgets.QWidget):

    def __init__(self, parent = None):
        super(Add_Info, self).__init__(parent)
        self.setupUi()


    def setupUi(self):

        self.setObjectName("Add_Info")
        self.resize(800, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMaximumSize(QtCore.QSize(800, 300))
        self.formLayout = QtWidgets.QFormLayout(self)
        self.formLayout.setObjectName("formLayout")
        self.frame = QtWidgets.QFrame(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 2)
        self.info_frame = QtWidgets.QFrame(self.frame)
        self.info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_frame.setObjectName("info_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.info_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.path_label = QtWidgets.QLabel(self.info_frame)
        self.path_label.setObjectName("path_label")
        self.gridLayout_2.addWidget(self.path_label, 1, 0, 1, 1)
        self.path_lineEdit = QtWidgets.QLineEdit(self.info_frame)
        self.path_lineEdit.setObjectName("path_lineEdit")
        self.gridLayout_2.addWidget(self.path_lineEdit, 1, 1, 1, 3)
        #self.version_label = QtWidgets.QLabel(self.info_frame)
        #self.version_label.setObjectName("version_label")
        #self.gridLayout_2.addWidget(self.version_label, 1, 0, 1, 1)
        #self.version_lineEdit = QtWidgets.QLineEdit(self.info_frame)
        #self.version_lineEdit.setObjectName("version_lineEdit")
        #self.gridLayout_2.addWidget(self.version_lineEdit, 1, 1, 1, 3)
        self.pathSearch_toolButton = QtWidgets.QToolButton(self.info_frame)
        self.pathSearch_toolButton.setObjectName("pathSearch_toolButton")
        self.gridLayout_2.addWidget(self.pathSearch_toolButton, 1, 4, 1, 1)
        self.Refname_label = QtWidgets.QLabel(self.info_frame)
        self.Refname_label.setObjectName("Refname_label")
        self.gridLayout_2.addWidget(self.Refname_label, 0, 0, 1, 1)
        self.Refname_lineEdit = QtWidgets.QLineEdit(self.info_frame)
        self.Refname_lineEdit.setObjectName("Refname_lineEdit")
        self.gridLayout_2.addWidget(self.Refname_lineEdit, 0, 1, 1, 3)
        self.gridLayout.addWidget(self.info_frame, 4, 0, 1, 2)
        self.Save_pushButton = QtWidgets.QPushButton(self.frame)
        self.Save_pushButton.setObjectName("Save_pushButton")
        self.gridLayout.addWidget(self.Save_pushButton, 5, 1, 1, 1)
        self.Cancel_pushButton = QtWidgets.QPushButton(self.frame)
        self.Cancel_pushButton.setObjectName("Cancel_pushButton")
        self.gridLayout.addWidget(self.Cancel_pushButton, 5, 0, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Add_Info):
        _translate = QtCore.QCoreApplication.translate
        Add_Info.setWindowTitle(_translate("Add_Info", "Add_Information"))
        self.label_5.setText(_translate("Add_Info", "Add new info"))
        self.path_label.setText(_translate("Add_Info", "info:"))
        self.pathSearch_toolButton.setText(_translate("Add_Info", "Search..."))
        self.Refname_label.setText(_translate("Add_Info", "Info Name:"))
        self.Save_pushButton.setText(_translate("Add_Info", "Save"))
        self.Cancel_pushButton.setText(_translate("Add_Info", "Cancel"))
