# -*- coding: utf-8 -*-

# Add_tags implementation generated from reading ui file '/home/jarvis/git/Powercall2/Powercall/Add_tags.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_tags(object):
    def setupUi(self):
        self.setObjectName("Add_tags")
        self.resize(639, 683)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.treeWidget = QtWidgets.QTreeWidget(self.frame)
        self.treeWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(461, 548))
        self.treeWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treeWidget.setAcceptDrops(False)
        self.treeWidget.setAutoFillBackground(True)
        self.treeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.treeWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.treeWidget.setAutoExpandDelay(-1)
        self.treeWidget.setIndentation(20)
        self.treeWidget.setRootIsDecorated(True)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setAllColumnsShowFocus(False)
        self.treeWidget.setHeaderHidden(False)
        self.treeWidget.setColumnCount(1)
        self.treeWidget.setObjectName("treeWidget")

        item_pre_alig = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_pre_alig.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate|item_pre_alig.flags())
        item_adapt = QtWidgets.QTreeWidgetItem(item_pre_alig)
        item_adapt.setFlags(item_adapt.flags() | QtCore.Qt.ItemIsUserCheckable)
        item_adapt.setCheckState(0, QtCore.Qt.Unchecked)
        item_len_filt = QtWidgets.QTreeWidgetItem(item_pre_alig)
        item_len_filt.setFlags(item_len_filt.flags() | QtCore.Qt.ItemIsUserCheckable)
        item_len_filt.setCheckState(0, QtCore.Qt.Unchecked)
        item_q_filt = QtWidgets.QTreeWidgetItem(item_pre_alig)
        item_q_filt.setFlags(item_q_filt.flags() | QtCore.Qt.ItemIsUserCheckable)
        item_q_filt.setCheckState(0, QtCore.Qt.Unchecked)
        item_fq_qc = QtWidgets.QTreeWidgetItem(item_pre_alig)
        item_fq_qc.setFlags(item_fq_qc.flags() | QtCore.Qt.ItemIsUserCheckable)
        item_fq_qc.setCheckState(0, QtCore.Qt.Unchecked)

        item_align = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_align.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate|item_align.flags())      
        item_umi = QtWidgets.QTreeWidgetItem(item_align)
        item_umi.setFlags(item_umi.flags() | QtCore.Qt.ItemIsUserCheckable)
        item_umi.setCheckState(0, QtCore.Qt.Unchecked)
        item_alig = QtWidgets.QTreeWidgetItem(item_align)
        item_alig.setFlags(item_alig.flags() | QtCore.Qt.ItemIsUserCheckable)
        item_alig.setCheckState(0, QtCore.Qt.Unchecked)
        item_sambam = QtWidgets.QTreeWidgetItem(item_align)
        item_sambam.setFlags(item_sambam.flags() | QtCore.Qt.ItemIsUserCheckable)
        item_sambam.setCheckState(0, QtCore.Qt.Unchecked)
        item_sort = QtWidgets.QTreeWidgetItem(item_align)
        item_sort.setFlags(item_sort.flags() | QtCore.Qt.ItemIsUserCheckable)
        item_sort.setCheckState(0, QtCore.Qt.Unchecked)
        item_bam_qc = QtWidgets.QTreeWidgetItem(item_align)
        item_bam_qc.setFlags(item_bam_qc.flags() | QtCore.Qt.ItemIsUserCheckable)
        item_bam_qc.setCheckState(0, QtCore.Qt.Unchecked)

        item_pre_proc = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_pre_proc.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate|item_pre_proc.flags())      
       
        item_bam_filt = QtWidgets.QTreeWidgetItem(item_pre_proc)
        item_bam_filt.setFlags(item_bam_qc.flags() | QtCore.Qt.ItemIsUserCheckable)
        item_bam_filt.setCheckState(0, QtCore.Qt.Unchecked)
        item_rgroup = QtWidgets.QTreeWidgetItem(item_pre_proc)
        item_rgroup.setFlags(item_rgroup.flags() | QtCore.Qt.ItemIsUserCheckable)
        item_rgroup.setCheckState(0, QtCore.Qt.Unchecked)
        item_dup = QtWidgets.QTreeWidgetItem(item_pre_proc)
        item_dup.setFlags(item_dup.flags() | QtCore.Qt.ItemIsUserCheckable)
        item_dup.setCheckState(0, QtCore.Qt.Unchecked)
        item_realig = QtWidgets.QTreeWidgetItem(item_pre_proc)
        item_realig.setFlags(item_realig.flags() | QtCore.Qt.ItemIsUserCheckable)
        item_realig.setCheckState(0, QtCore.Qt.Unchecked)
        item_bqsr = QtWidgets.QTreeWidgetItem(item_pre_proc)
        item_bqsr.setFlags(item_bqsr.flags() | QtCore.Qt.ItemIsUserCheckable)
        item_bqsr.setCheckState(0, QtCore.Qt.Unchecked)

        item_vcalling = QtWidgets.QTreeWidgetItem(self.treeWidget)     
        item_vcalling.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate|item_vcalling.flags())      
    
        item_shortv_call = QtWidgets.QTreeWidgetItem(item_vcalling)
        item_shortv_call.setFlags(item_shortv_call.flags() | QtCore.Qt.ItemIsUserCheckable)
        item_shortv_call.setCheckState(0, QtCore.Qt.Unchecked)
        item_cnv_call = QtWidgets.QTreeWidgetItem(item_vcalling)
        item_cnv_call.setFlags(item_cnv_call.flags() | QtCore.Qt.ItemIsUserCheckable)
        item_cnv_call.setCheckState(0, QtCore.Qt.Unchecked)

        item_post_proc = QtWidgets.QTreeWidgetItem(self.treeWidget)     
        item_post_proc.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate|item_post_proc.flags())      
    
        item_vcf_norm = QtWidgets.QTreeWidgetItem(item_post_proc)
        item_vcf_norm.setFlags(item_vcf_norm.flags() | QtCore.Qt.ItemIsUserCheckable)
        item_vcf_norm.setCheckState(0, QtCore.Qt.Unchecked)
        item_vcf_filt = QtWidgets.QTreeWidgetItem(item_post_proc)
        item_vcf_filt.setFlags(item_vcf_filt.flags() | QtCore.Qt.ItemIsUserCheckable)
        item_vcf_filt.setCheckState(0, QtCore.Qt.Unchecked)
        item_vcf_to_tsv = QtWidgets.QTreeWidgetItem(item_post_proc)
        item_vcf_to_tsv.setFlags(item_vcf_to_tsv.flags() | QtCore.Qt.ItemIsUserCheckable)
        item_vcf_to_tsv.setCheckState(0, QtCore.Qt.Unchecked)
        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setCascadingSectionResizes(True)
        self.treeWidget.header().setDefaultSectionSize(300)
        self.treeWidget.header().setHighlightSections(False)
        self.treeWidget.header().setMinimumSectionSize(100)
        self.treeWidget.header().setSortIndicatorShown(False)
        self.treeWidget.header().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.treeWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Add_tags", "Add_tags"))
        self.label.setText(_translate("Add_tags", "Add or Remove Tags"))
        self.treeWidget.headerItem().setText(0, _translate("Add_tags", "Analysis Steps"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Add_tags", "Pre-Alignment"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("Add_tags", "Adapters trimming"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("Add_tags", "FASTQ read lenght filter"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("Add_tags", "FASTQ quality filter"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("Add_tags", "FASTQ quality control"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Add_tags", "Alignment"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("Add_tags", "UMI/Molecular barcodes merge"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("Add_tags", "FASTQ alignment"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("Add_tags", "SAM to BAM convertion"))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("Add_tags", "BAM sort"))
        self.treeWidget.topLevelItem(1).child(4).setText(0, _translate("Add_tags", "BAM quality control"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("Add_tags", "Pre-Processing"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("Add_tags", "BAM filter"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("Add_tags", "Add readgroups to BAM"))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("Add_tags", "PCR duplicates marking"))
        self.treeWidget.topLevelItem(2).child(3).setText(0, _translate("Add_tags", "InDels realignment"))
        self.treeWidget.topLevelItem(2).child(4).setText(0, _translate("Add_tags", "Base quality recalibration"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("Add_tags", "Variant Calling"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("Add_tags", "SNV & short InDels"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("Add_tags", "Copy Number Variation"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("Add_tags", "Post-Processing"))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("Add_tags", "VCF filter"))
        self.treeWidget.topLevelItem(4).child(1).setText(0, _translate("Add_tags", "Hard filter"))
        self.treeWidget.topLevelItem(4).child(2).setText(0, _translate("Add_tags", "VCF to TSV convertion"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("Add_tags", "Annotation"))
        self.treeWidget.topLevelItem(5).child(0).setText(0, _translate("Add_tags", "SNV & short InDels"))
        self.treeWidget.topLevelItem(5).child(1).setText(0, _translate("Add_tags", "Copy Number Variation"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
